import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Space Grotesk', 'sans-serif'],
                'headline-md': ['Space Grotesk', 'sans-serif'],
                'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
                'display-lg': ['Space Grotesk', 'sans-serif'],
                'body-sm': ['Space Grotesk', 'sans-serif'],
                'label-bold': ['Space Grotesk', 'sans-serif'],
            },
            fontSize: {
                'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
                'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
                'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'label-bold': ['12px', { lineHeight: '1', fontWeight: '700' }],
            },
            colors: {
                'primary-container': '#800000',
                'error-container': '#ffdad6',
                'primary-fixed-dim': '#ffb4a8',
                'on-background': '#1a1c1c',
                'on-secondary': '#ffffff',
                'tertiary': '#00137f',
                'tertiary-container': '#0021b9',
                'surface-card': '#FFFFFF',
                'on-primary-fixed': '#410000',
                'error': '#ba1a1a',
                'on-surface': '#1a1c1c',
                'tertiary-fixed-dim': '#bcc2ff',
                'on-surface-variant': '#5a413d',
                'secondary-fixed': '#e2e2e2',
                'status-done': '#10B981',
                'surface-container-lowest': '#ffffff',
                'secondary-container': '#e2e2e2',
                'outline-variant': '#e2bfb9',
                'on-secondary-fixed': '#1b1b1b',
                'on-primary': '#ffffff',
                'inverse-surface': '#2f3131',
                'background': '#f9f9f9',
                'secondary': '#5e5e5e',
                'surface-container-low': '#f3f3f4',
                'surface-dim': '#dadada',
                'primary': '#570000',
                'border-heavy': '#000000',
                'on-secondary-container': '#646464',
                'outline': '#8e706c',
                'surface-tint': '#b22b1d',
                'surface-container-highest': '#e2e2e2',
                'on-primary-container': '#ff8371',
                'inverse-on-surface': '#f0f1f1',
                'on-error-container': '#93000a',
                'tertiary-fixed': '#dfe0ff',
                'surface-variant': '#e2e2e2',
                'surface-bright': '#f9f9f9',
                'inverse-primary': '#ffb4a8',
                'secondary-fixed-dim': '#c6c6c6',
                'on-tertiary-fixed': '#000c61',
                'on-tertiary-fixed-variant': '#1830c2',
                'on-primary-fixed-variant': '#8f0f07',
                'status-todo': '#3B82F6',
                'status-progress': '#F59E0B',
                'on-error': '#ffffff',
                'on-secondary-fixed-variant': '#474747',
                'on-tertiary': '#ffffff',
                'status-late': '#EF4444',
                'surface': '#f9f9f9',
                'surface-container-high': '#e8e8e8',
                'surface-container': '#eeeeee',
                'primary-fixed': '#ffdad4',
                'on-tertiary-container': '#94a0ff',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                'margin-mobile': '16px',
                'border-width': '4px',
                'margin-desktop': '40px',
                'gutter': '24px',
                'base': '8px',
                'shadow-offset': '6px',
            },
        },
    },

    plugins: [forms],
};